version: '3.8'
services:
  user-service:
    build:
      context: ./EchoScribe.UserService
      dockerfile: Dockerfile
    ports:
      - "5001:80"

  post-service:
    build:
      context: ./EchoScribe.PostService
      dockerfile: Dockerfile
    ports:
      - "5002:80"

  comment-service:
    build:
      context: ./EchoScribe.CommentService
      dockerfile: Dockerfile
    ports:
      - "5003:80"

  nginx-gateway:
    build:
      context: ./gateway/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - user-service
      - post-service
      - comment-service